// 
// Decompiled by Procyon v0.5.36
// 

package org.opensaml.xml.security;

import org.opensaml.xml.security.keyinfo.KeyInfoCredentialResolver;
import org.opensaml.xml.security.keyinfo.NamedKeyInfoGeneratorManager;
import java.security.interfaces.DSAParams;
import org.opensaml.xml.security.credential.Credential;

public interface SecurityConfiguration
{
    String getSignatureAlgorithmURI(final String p0);
    
    String getSignatureAlgorithmURI(final Credential p0);
    
    String getSignatureReferenceDigestMethod();
    
    String getSignatureCanonicalizationAlgorithm();
    
    Integer getSignatureHMACOutputLength();
    
    String getDataEncryptionAlgorithmURI(final String p0, final Integer p1);
    
    String getDataEncryptionAlgorithmURI(final Credential p0);
    
    String getKeyTransportEncryptionAlgorithmURI(final String p0, final Integer p1, final String p2);
    
    String getKeyTransportEncryptionAlgorithmURI(final Credential p0, final String p1);
    
    String getAutoGeneratedDataEncryptionKeyAlgorithmURI();
    
    DSAParams getDSAParams(final int p0);
    
    NamedKeyInfoGeneratorManager getKeyInfoGeneratorManager();
    
    KeyInfoCredentialResolver getKeyInfoCredentialResolver(final String p0);
    
    KeyInfoCredentialResolver getDefaultKeyInfoCredentialResolver();
}
